#!/usr/bin/python

from PySide6.QtCore import QSettings, QLocale

# Ogni voce qui sotto e' un testo visibile in UI e va tradotta in tutte le lingue.
# {website} e {appName} vengono sostituiti automaticamente dopo il caricamento.
_TRANSLATIONS = {

    # inglese
    'en': {
        'aboutVersion': 'Version: %s',
        'aboutWebsite': 'Website: {website}',
        'aboutPrivacy': 'Privacy: we anonymously collect app version and operating system for aggregate usage statistics.',
        'btnDefault': ' Paste and Download',
        'btnReverse': ' Please wait...',
        'downloadPathError': 'The download folder is not accessible',
        'internetError': 'There is no internet connection, it may be blocked by the antivirus or firewall',
        'noLinks': 'There are no links waiting for download',
        'txtUpdatesHtml': 'The new version <br><b>%s</b><br> is available!<br><br>Go to {website}<br>',
        'txtUpdatesTxt': 'New version %s available!',
        'txtUpdatesNo': '{appName} is already updated<br>',
        'txtUpdatesError': 'Unable to check for updates',
        'ytDlpUpdating': 'Please wait, updating internal libraries...',
        'ytDlpUpdateDone': 'Internal libraries updated',
        'installFailedMsg': 'Unable to install internal libraries, so {appName} will close now. Run it again to retry.',
        'btnClose': 'Close',
        'setupCompleteMsg': 'All done, you can start!',
        'confirmExitTitle': 'Confirm exit',
        'confirmExitMsg': 'A download is in progress. Are you sure you want to exit? It will be stopped.',
        'restartRequired': 'Restart {appName} for the changes to take effect.',
        'titleError': 'Error',
        'titleUpdates': 'Updates',
        'titleRestart': 'Restart required',
        'msgContentCopied': 'Content is copied',
        'msgFoundLinks': 'Found %s valid links',
        'msgNoValidLinks': 'No valid links found',
        'msgInvalidPastylink': 'The link was copied incorrectly, go back to Pastylink and try again',
        'msgDownloadStarted': 'Download started...',
        'msgDownloadFinished': 'Download finished in %s seconds',
        'typeDownload': 'Download',
        'typeConversion': 'Conversion',
        'msgInProgress': ' in progress for item no. %s',
        'colUrl': 'Url',
        'colState': 'State',
        'colStatusCode': 'StatusCode',
        'colSaveAs': 'SaveAs',
        'colActions': 'Actions',
        'ctxCopyLink': 'Copy link address',
        'ctxOpenFolder': 'Open download folder',
        'ctxDownloadNow': 'Download now',
        'ctxConvertMp3': 'Convert to mp3 audio',
        'ctxStop': 'Stop',
        'ctxRemove': 'Remove',
        'ctxDeleteAndRemove': 'Delete file and Remove',
        'menuFile': 'File',
        'menuEdit': 'Edit',
        'menuHelp': 'Help',
        'actionExit': 'Exit',
        'actionStartWaiting': 'Start waiting links',
        'actionStopAll': 'Stop All',
        'actionRemoveAll': 'Remove all',
        'actionPreferences': 'Preferences',
        'actionCheckUpdates': 'Check for updates',
        'actionAbout': 'About',
        'prefsTitle': 'Preferences',
        'downloadFolderLabel': 'Download Folder',
        'selectButton': 'Select',
        'videoGroupLabel': 'Video',
        'convNever': 'Never convert',
        'convDeleteVideo': 'Convert always to audio and delete video',
        'convKeepVideo': 'Convert always to audio and keep video',
        'afterDownloadLabel': 'After download',
        'doOpenFolder': 'Open the downloads folder',
        'doNothing': 'Do nothing',
        'languageLabel': 'Language',
        'themeLabel': 'Theme',
        'themeSystem': 'System (default)',
        'themeLight': 'Light',
        'themeDark': 'Dark',
    },

    # italiano
    'it': {
        'aboutVersion': 'Versione: %s',
        'aboutWebsite': 'Sito: {website}',
        'aboutPrivacy': 'Privacy: raccogliamo in forma anonima versione dell\'app e sistema operativo per statistiche d\'uso aggregate.',
        'btnDefault': ' Incolla e Scarica',
        'btnReverse': ' Attendere...',
        'downloadPathError': 'La cartella di download non è accessibile',
        'internetError': "Non c'è connessione a internet, potrebbe essere bloccata dall'antivirus o dal firewall",
        'noLinks': 'Non ci sono link in attesa di download',
        'txtUpdatesHtml': 'La nuova versione <br><b>%s</b><br> è disponibile!<br><br>Vai su {website}<br>',
        'txtUpdatesTxt': 'Nuova versione %s disponibile!',
        'txtUpdatesNo': '{appName} è già aggiornato<br>',
        'txtUpdatesError': 'Impossibile verificare gli aggiornamenti',
        'ytDlpUpdating': 'Attendere, aggiornamento delle librerie interne in corso...',
        'ytDlpUpdateDone': 'Librerie interne aggiornate',
        'installFailedMsg': 'Impossibile installare le librerie interne, quindi {appName} verrà chiuso. Rilancialo per riprovare.',
        'btnClose': 'Chiudi',
        'setupCompleteMsg': 'Tutto fatto, puoi iniziare!',
        'confirmExitTitle': 'Conferma uscita',
        'confirmExitMsg': 'È in corso un download. Sei sicuro di voler uscire? Verrà interrotto.',
        'restartRequired': 'Riavvia {appName} perché le modifiche abbiano effetto.',
        'titleError': 'Errore',
        'titleUpdates': 'Aggiornamenti',
        'titleRestart': 'Riavvio necessario',
        'msgContentCopied': 'Contenuto copiato',
        'msgFoundLinks': 'Trovati %s link validi',
        'msgNoValidLinks': 'Nessun link valido trovato',
        'msgInvalidPastylink': 'Il link è stato copiato male, torna su Pastylink e riprova',
        'msgDownloadStarted': 'Download avviato...',
        'msgDownloadFinished': 'Download completato in %s secondi',
        'typeDownload': 'Download',
        'typeConversion': 'Conversione',
        'msgInProgress': " in corso per l'elemento n. %s",
        'colUrl': 'Url',
        'colState': 'Stato',
        'colStatusCode': 'CodiceStato',
        'colSaveAs': 'SalvaCome',
        'colActions': 'Azioni',
        'ctxCopyLink': 'Copia indirizzo link',
        'ctxOpenFolder': 'Apri cartella di download',
        'ctxDownloadNow': 'Scarica ora',
        'ctxConvertMp3': 'Converti in mp3',
        'ctxStop': 'Ferma',
        'ctxRemove': 'Rimuovi',
        'ctxDeleteAndRemove': 'Elimina file e rimuovi',
        'menuFile': 'File',
        'menuEdit': 'Modifica',
        'menuHelp': 'Aiuto',
        'actionExit': 'Esci',
        'actionStartWaiting': 'Avvia link in attesa',
        'actionStopAll': 'Ferma tutto',
        'actionRemoveAll': 'Rimuovi tutto',
        'actionPreferences': 'Preferenze',
        'actionCheckUpdates': 'Controlla aggiornamenti',
        'actionAbout': 'Informazioni',
        'prefsTitle': 'Preferenze',
        'downloadFolderLabel': 'Cartella di Download',
        'selectButton': 'Seleziona',
        'videoGroupLabel': 'Video',
        'convNever': 'Non convertire mai',
        'convDeleteVideo': "Converti sempre in audio ed elimina il video",
        'convKeepVideo': 'Converti sempre in audio e mantieni il video',
        'afterDownloadLabel': 'Dopo il download',
        'doOpenFolder': 'Apri la cartella dei download',
        'doNothing': 'Non fare nulla',
        'languageLabel': 'Lingua',
        'themeLabel': 'Tema',
        'themeSystem': 'Sistema (predefinito)',
        'themeLight': 'Chiaro',
        'themeDark': 'Scuro',
    },

    # francese
    'fr': {
        'aboutVersion': 'Version : %s',
        'aboutWebsite': 'Site : {website}',
        'aboutPrivacy': 'Confidentialité : nous collectons de manière anonyme la version de l\'application et le système d\'exploitation à des fins de statistiques d\'utilisation agrégées.',
        'btnDefault': ' Coller et Télécharger',
        'btnReverse': ' Veuillez patienter...',
        'downloadPathError': "Le dossier de téléchargement n'est pas accessible",
        'internetError': "Il n'y a pas de connexion internet, elle est peut-être bloquée par l'antivirus ou le pare-feu",
        'noLinks': "Il n'y a aucun lien en attente de téléchargement",
        'txtUpdatesHtml': 'La nouvelle version <br><b>%s</b><br> est disponible !<br><br>Allez sur {website}<br>',
        'txtUpdatesTxt': 'Nouvelle version %s disponible !',
        'txtUpdatesNo': '{appName} est déjà à jour<br>',
        'txtUpdatesError': 'Impossible de vérifier les mises à jour',
        'ytDlpUpdating': 'Veuillez patienter, mise à jour des bibliothèques internes...',
        'ytDlpUpdateDone': 'Bibliothèques internes mises à jour',
        'installFailedMsg': 'Impossible d\'installer les librairies internes, {appName} va donc se fermer. Relancez-le pour réessayer.',
        'btnClose': 'Fermer',
        'setupCompleteMsg': 'Tout est prêt, vous pouvez commencer !',
        'confirmExitTitle': 'Confirmer la fermeture',
        'confirmExitMsg': 'Un téléchargement est en cours. Voulez-vous vraiment quitter ? Il sera interrompu.',
        'restartRequired': 'Redémarrez {appName} pour que les modifications prennent effet.',
        'titleError': 'Erreur',
        'titleUpdates': 'Mises à jour',
        'titleRestart': 'Redémarrage requis',
        'msgContentCopied': 'Contenu copié',
        'msgFoundLinks': '%s liens valides trouvés',
        'msgNoValidLinks': 'Aucun lien valide trouvé',
        'msgInvalidPastylink': 'Le lien a été copié incorrectement, retournez sur Pastylink et réessayez',
        'msgDownloadStarted': 'Téléchargement démarré...',
        'msgDownloadFinished': 'Téléchargement terminé en %s secondes',
        'typeDownload': 'Téléchargement',
        'typeConversion': 'Conversion',
        'msgInProgress': " en cours pour l'élément n° %s",
        'colUrl': 'Url',
        'colState': 'État',
        'colStatusCode': 'CodeÉtat',
        'colSaveAs': 'Enregistré',
        'colActions': 'Actions',
        'ctxCopyLink': "Copier l'adresse du lien",
        'ctxOpenFolder': 'Ouvrir le dossier de téléchargement',
        'ctxDownloadNow': 'Télécharger maintenant',
        'ctxConvertMp3': 'Convertir en mp3',
        'ctxStop': 'Arrêter',
        'ctxRemove': 'Supprimer',
        'ctxDeleteAndRemove': 'Supprimer le fichier et la ligne',
        'menuFile': 'Fichier',
        'menuEdit': 'Édition',
        'menuHelp': 'Aide',
        'actionExit': 'Quitter',
        'actionStartWaiting': 'Démarrer les liens en attente',
        'actionStopAll': 'Tout arrêter',
        'actionRemoveAll': 'Tout supprimer',
        'actionPreferences': 'Préférences',
        'actionCheckUpdates': 'Vérifier les mises à jour',
        'actionAbout': 'À propos',
        'prefsTitle': 'Préférences',
        'downloadFolderLabel': 'Dossier de téléchargement',
        'selectButton': 'Sélectionner',
        'videoGroupLabel': 'Vidéo',
        'convNever': 'Ne jamais convertir',
        'convDeleteVideo': 'Toujours convertir en audio et supprimer la vidéo',
        'convKeepVideo': 'Toujours convertir en audio et conserver la vidéo',
        'afterDownloadLabel': 'Après le téléchargement',
        'doOpenFolder': 'Ouvrir le dossier de téléchargements',
        'doNothing': 'Ne rien faire',
        'languageLabel': 'Langue',
        'themeLabel': 'Thème',
        'themeSystem': 'Système (par défaut)',
        'themeLight': 'Clair',
        'themeDark': 'Sombre',
    },

    # spagnolo
    'es': {
        'aboutVersion': 'Versión: %s',
        'aboutWebsite': 'Web: {website}',
        'aboutPrivacy': 'Privacidad: recopilamos de forma anónima la versión de la app y el sistema operativo para estadísticas de uso agregadas.',
        'btnDefault': ' Pegar y Descargar',
        'btnReverse': ' Espere por favor...',
        'downloadPathError': 'La carpeta de descarga no es accesible',
        'internetError': 'No hay conexión a internet, puede estar bloqueada por el antivirus o el firewall',
        'noLinks': 'No hay enlaces esperando para descargar',
        'txtUpdatesHtml': 'La nueva versión <br><b>%s</b><br> está disponible!<br><br>Ve a {website}<br>',
        'txtUpdatesTxt': '¡Nueva versión %s disponible!',
        'txtUpdatesNo': '{appName} ya está actualizado<br>',
        'txtUpdatesError': 'No se pueden comprobar actualizaciones',
        'ytDlpUpdating': 'Espere por favor, actualizando las librerías internas...',
        'ytDlpUpdateDone': 'Librerías internas actualizadas',
        'installFailedMsg': 'No se han podido instalar las librerías internas, por lo que {appName} se cerrará. Vuelve a abrirlo para reintentarlo.',
        'btnClose': 'Cerrar',
        'setupCompleteMsg': '¡Todo listo, puedes empezar!',
        'confirmExitTitle': 'Confirmar salida',
        'confirmExitMsg': 'Hay una descarga en curso. ¿Seguro que quieres salir? Se detendrá.',
        'restartRequired': 'Reinicia {appName} para que los cambios tengan efecto.',
        'titleError': 'Error',
        'titleUpdates': 'Actualizaciones',
        'titleRestart': 'Reinicio necesario',
        'msgContentCopied': 'Contenido copiado',
        'msgFoundLinks': 'Se encontraron %s enlaces válidos',
        'msgNoValidLinks': 'No se encontró ningún enlace válido',
        'msgInvalidPastylink': 'El enlace se copió incorrectamente, vuelve a Pastylink e inténtalo de nuevo',
        'msgDownloadStarted': 'Descarga iniciada...',
        'msgDownloadFinished': 'Descarga completada en %s segundos',
        'typeDownload': 'Descarga',
        'typeConversion': 'Conversión',
        'msgInProgress': ' en curso para el elemento n.º %s',
        'colUrl': 'Url',
        'colState': 'Estado',
        'colStatusCode': 'CódigoEstado',
        'colSaveAs': 'GuardarComo',
        'colActions': 'Acciones',
        'ctxCopyLink': 'Copiar dirección del enlace',
        'ctxOpenFolder': 'Abrir carpeta de descarga',
        'ctxDownloadNow': 'Descargar ahora',
        'ctxConvertMp3': 'Convertir a mp3',
        'ctxStop': 'Detener',
        'ctxRemove': 'Eliminar',
        'ctxDeleteAndRemove': 'Eliminar archivo y quitar',
        'menuFile': 'Archivo',
        'menuEdit': 'Editar',
        'menuHelp': 'Ayuda',
        'actionExit': 'Salir',
        'actionStartWaiting': 'Iniciar enlaces en espera',
        'actionStopAll': 'Detener todo',
        'actionRemoveAll': 'Eliminar todo',
        'actionPreferences': 'Preferencias',
        'actionCheckUpdates': 'Buscar actualizaciones',
        'actionAbout': 'Acerca de',
        'prefsTitle': 'Preferencias',
        'downloadFolderLabel': 'Carpeta de Descarga',
        'selectButton': 'Seleccionar',
        'videoGroupLabel': 'Vídeo',
        'convNever': 'No convertir nunca',
        'convDeleteVideo': 'Convertir siempre a audio y eliminar el vídeo',
        'convKeepVideo': 'Convertir siempre a audio y mantener el vídeo',
        'afterDownloadLabel': 'Después de la descarga',
        'doOpenFolder': 'Abrir la carpeta de descargas',
        'doNothing': 'No hacer nada',
        'languageLabel': 'Idioma',
        'themeLabel': 'Tema',
        'themeSystem': 'Sistema (predeterminado)',
        'themeLight': 'Claro',
        'themeDark': 'Oscuro',
    },

    # tedesco
    'de': {
        'aboutVersion': 'Version: %s',
        'aboutWebsite': 'Webseite: {website}',
        'aboutPrivacy': 'Datenschutz: Wir erfassen anonym die App-Version und das Betriebssystem für aggregierte Nutzungsstatistiken.',
        'btnDefault': ' Einfügen und Herunterladen',
        'btnReverse': ' Bitte warten...',
        'downloadPathError': 'Der Download-Ordner ist nicht zugänglich',
        'internetError': 'Keine Internetverbindung, sie könnte von Antivirus oder Firewall blockiert sein',
        'noLinks': 'Es gibt keine Links, die auf den Download warten',
        'txtUpdatesHtml': 'Die neue Version <br><b>%s</b><br> ist verfügbar!<br><br>Gehe zu {website}<br>',
        'txtUpdatesTxt': 'Neue Version %s verfügbar!',
        'txtUpdatesNo': '{appName} ist bereits aktuell<br>',
        'txtUpdatesError': 'Updates konnten nicht überprüft werden',
        'ytDlpUpdating': 'Bitte warten, interne Bibliotheken werden aktualisiert...',
        'ytDlpUpdateDone': 'Interne Bibliotheken aktualisiert',
        'installFailedMsg': 'Interne Bibliotheken konnten nicht installiert werden, daher wird {appName} jetzt geschlossen. Starte es erneut, um es noch einmal zu versuchen.',
        'btnClose': 'Schließen',
        'setupCompleteMsg': 'Fertig, du kannst loslegen!',
        'confirmExitTitle': 'Beenden bestätigen',
        'confirmExitMsg': 'Ein Download läuft gerade. Möchtest du wirklich beenden? Er wird abgebrochen.',
        'restartRequired': 'Starte {appName} neu, damit die Änderungen wirksam werden.',
        'titleError': 'Fehler',
        'titleUpdates': 'Updates',
        'titleRestart': 'Neustart erforderlich',
        'msgContentCopied': 'Inhalt kopiert',
        'msgFoundLinks': '%s gültige Links gefunden',
        'msgNoValidLinks': 'Kein gültiger Link gefunden',
        'msgInvalidPastylink': 'Der Link wurde falsch kopiert, gehe zurück zu Pastylink und versuche es erneut',
        'msgDownloadStarted': 'Download gestartet...',
        'msgDownloadFinished': 'Download in %s Sekunden abgeschlossen',
        'typeDownload': 'Download',
        'typeConversion': 'Umwandlung',
        'msgInProgress': ' läuft für Element Nr. %s',
        'colUrl': 'Url',
        'colState': 'Status',
        'colStatusCode': 'Statuscode',
        'colSaveAs': 'Speicherort',
        'colActions': 'Aktionen',
        'ctxCopyLink': 'Link-Adresse kopieren',
        'ctxOpenFolder': 'Download-Ordner öffnen',
        'ctxDownloadNow': 'Jetzt herunterladen',
        'ctxConvertMp3': 'In mp3 umwandeln',
        'ctxStop': 'Stopp',
        'ctxRemove': 'Entfernen',
        'ctxDeleteAndRemove': 'Datei löschen und entfernen',
        'menuFile': 'Datei',
        'menuEdit': 'Bearbeiten',
        'menuHelp': 'Hilfe',
        'actionExit': 'Beenden',
        'actionStartWaiting': 'Wartende Links starten',
        'actionStopAll': 'Alle stoppen',
        'actionRemoveAll': 'Alle entfernen',
        'actionPreferences': 'Einstellungen',
        'actionCheckUpdates': 'Nach Updates suchen',
        'actionAbout': 'Über',
        'prefsTitle': 'Einstellungen',
        'downloadFolderLabel': 'Download-Ordner',
        'selectButton': 'Auswählen',
        'videoGroupLabel': 'Video',
        'convNever': 'Nie umwandeln',
        'convDeleteVideo': 'Immer in Audio umwandeln und Video löschen',
        'convKeepVideo': 'Immer in Audio umwandeln und Video behalten',
        'afterDownloadLabel': 'Nach dem Download',
        'doOpenFolder': 'Download-Ordner öffnen',
        'doNothing': 'Nichts tun',
        'languageLabel': 'Sprache',
        'themeLabel': 'Design',
        'themeSystem': 'System (Standard)',
        'themeLight': 'Hell',
        'themeDark': 'Dunkel',
    },

    # cinese semplificato
    'zh': {
        'aboutVersion': '版本：%s',
        'aboutWebsite': '网站：{website}',
        'aboutPrivacy': '隐私：我们匿名收集应用版本和操作系统信息，用于汇总使用统计。',
        'btnDefault': ' 粘贴并下载',
        'btnReverse': ' 请稍候...',
        'downloadPathError': '下载文件夹不可访问',
        'internetError': '没有网络连接，可能被防病毒软件或防火墙拦截',
        'noLinks': '没有等待下载的链接',
        'txtUpdatesHtml': '新版本 <br><b>%s</b><br> 已发布！<br><br>请访问 {website}<br>',
        'txtUpdatesTxt': '新版本 %s 可用！',
        'txtUpdatesNo': '{appName} 已是最新版本<br>',
        'txtUpdatesError': '无法检查更新',
        'ytDlpUpdating': '请稍候，正在更新内部库...',
        'ytDlpUpdateDone': '内部库已更新',
        'installFailedMsg': '无法安装内部库，{appName} 即将关闭。请重新启动以重试。',
        'btnClose': '关闭',
        'setupCompleteMsg': '一切就绪，可以开始了！',
        'confirmExitTitle': '确认退出',
        'confirmExitMsg': '有一个下载任务正在进行。确定要退出吗？该下载将被中止。',
        'restartRequired': '重启 {appName} 以使更改生效。',
        'titleError': '错误',
        'titleUpdates': '更新',
        'titleRestart': '需要重启',
        'msgContentCopied': '内容已复制',
        'msgFoundLinks': '找到 %s 个有效链接',
        'msgNoValidLinks': '未找到有效链接',
        'msgInvalidPastylink': '链接复制有误，请返回 Pastylink 重试',
        'msgDownloadStarted': '下载已开始...',
        'msgDownloadFinished': '下载在 %s 秒内完成',
        'typeDownload': '下载',
        'typeConversion': '转换',
        'msgInProgress': ' 正在处理第 %s 项',
        'colUrl': '网址',
        'colState': '状态',
        'colStatusCode': '状态码',
        'colSaveAs': '保存为',
        'colActions': '操作',
        'ctxCopyLink': '复制链接地址',
        'ctxOpenFolder': '打开下载文件夹',
        'ctxDownloadNow': '立即下载',
        'ctxConvertMp3': '转换为mp3',
        'ctxStop': '停止',
        'ctxRemove': '移除',
        'ctxDeleteAndRemove': '删除文件并移除',
        'menuFile': '文件',
        'menuEdit': '编辑',
        'menuHelp': '帮助',
        'actionExit': '退出',
        'actionStartWaiting': '开始等待中的链接',
        'actionStopAll': '全部停止',
        'actionRemoveAll': '全部移除',
        'actionPreferences': '首选项',
        'actionCheckUpdates': '检查更新',
        'actionAbout': '关于',
        'prefsTitle': '首选项',
        'downloadFolderLabel': '下载文件夹',
        'selectButton': '选择',
        'videoGroupLabel': '视频',
        'convNever': '从不转换',
        'convDeleteVideo': '始终转换为音频并删除视频',
        'convKeepVideo': '始终转换为音频并保留视频',
        'afterDownloadLabel': '下载后',
        'doOpenFolder': '打开下载文件夹',
        'doNothing': '不执行任何操作',
        'languageLabel': '语言',
        'themeLabel': '主题',
        'themeSystem': '系统（默认）',
        'themeLight': '浅色',
        'themeDark': '深色',
    },

    # giapponese
    'ja': {
        'aboutVersion': 'バージョン: %s',
        'aboutWebsite': 'ウェブサイト: {website}',
        'aboutPrivacy': 'プライバシー：集計利用統計のため、アプリのバージョンとOSを匿名で収集します。',
        'btnDefault': ' 貼り付けてダウンロード',
        'btnReverse': ' お待ちください...',
        'downloadPathError': 'ダウンロードフォルダにアクセスできません',
        'internetError': 'インターネット接続がありません。ウイルス対策ソフトやファイアウォールでブロックされている可能性があります',
        'noLinks': 'ダウンロード待ちのリンクはありません',
        'txtUpdatesHtml': '新しいバージョン <br><b>%s</b><br> が利用可能です！<br><br>{website} へ移動<br>',
        'txtUpdatesTxt': '新しいバージョン %s が利用可能です！',
        'txtUpdatesNo': '{appName} は最新の状態です<br>',
        'txtUpdatesError': '更新を確認できません',
        'ytDlpUpdating': 'お待ちください、内部ライブラリを更新しています...',
        'ytDlpUpdateDone': '内部ライブラリを更新しました',
        'installFailedMsg': '内部ライブラリをインストールできなかったため、{appName} を終了します。再試行するには、もう一度起動してください。',
        'btnClose': '閉じる',
        'setupCompleteMsg': '準備完了です、始められます！',
        'confirmExitTitle': '終了の確認',
        'confirmExitMsg': 'ダウンロードが進行中です。本当に終了しますか？ダウンロードは中止されます。',
        'restartRequired': '変更を反映するには {appName} を再起動してください。',
        'titleError': 'エラー',
        'titleUpdates': 'アップデート',
        'titleRestart': '再起動が必要です',
        'msgContentCopied': 'コピーしました',
        'msgFoundLinks': '%s 件の有効なリンクが見つかりました',
        'msgNoValidLinks': '有効なリンクが見つかりませんでした',
        'msgInvalidPastylink': 'リンクのコピーに失敗しました。Pastylinkに戻ってもう一度お試しください',
        'msgDownloadStarted': 'ダウンロードを開始しました...',
        'msgDownloadFinished': 'ダウンロードが %s 秒で完了しました',
        'typeDownload': 'ダウンロード',
        'typeConversion': '変換',
        'msgInProgress': ' 項目 No. %s を処理中',
        'colUrl': 'URL',
        'colState': '状態',
        'colStatusCode': 'ステータスコード',
        'colSaveAs': '保存先',
        'colActions': '操作',
        'ctxCopyLink': 'リンクアドレスをコピー',
        'ctxOpenFolder': 'ダウンロードフォルダを開く',
        'ctxDownloadNow': '今すぐダウンロード',
        'ctxConvertMp3': 'mp3に変換',
        'ctxStop': '停止',
        'ctxRemove': '削除',
        'ctxDeleteAndRemove': 'ファイルを削除して除去',
        'menuFile': 'ファイル',
        'menuEdit': '編集',
        'menuHelp': 'ヘルプ',
        'actionExit': '終了',
        'actionStartWaiting': '待機中のリンクを開始',
        'actionStopAll': 'すべて停止',
        'actionRemoveAll': 'すべて削除',
        'actionPreferences': '環境設定',
        'actionCheckUpdates': '更新を確認',
        'actionAbout': 'このアプリについて',
        'prefsTitle': '環境設定',
        'downloadFolderLabel': 'ダウンロードフォルダ',
        'selectButton': '選択',
        'videoGroupLabel': 'ビデオ',
        'convNever': '変換しない',
        'convDeleteVideo': '常に音声に変換して動画を削除',
        'convKeepVideo': '常に音声に変換して動画を保持',
        'afterDownloadLabel': 'ダウンロード後',
        'doOpenFolder': 'ダウンロードフォルダを開く',
        'doNothing': '何もしない',
        'languageLabel': '言語',
        'themeLabel': 'テーマ',
        'themeSystem': 'システム（デフォルト）',
        'themeLight': 'ライト',
        'themeDark': 'ダーク',
    },

    # portoghese
    'pt': {
        'aboutVersion': 'Versão: %s',
        'aboutWebsite': 'Site: {website}',
        'aboutPrivacy': 'Privacidade: coletamos de forma anônima a versão do app e o sistema operacional para estatísticas de uso agregadas.',
        'btnDefault': ' Colar e Baixar',
        'btnReverse': ' Aguarde...',
        'downloadPathError': 'A pasta de download não está acessível',
        'internetError': 'Não há conexão com a internet, pode estar bloqueada pelo antivírus ou firewall',
        'noLinks': 'Não há links aguardando download',
        'txtUpdatesHtml': 'A nova versão <br><b>%s</b><br> está disponível!<br><br>Vá para {website}<br>',
        'txtUpdatesTxt': 'Nova versão %s disponível!',
        'txtUpdatesNo': '{appName} já está atualizado<br>',
        'txtUpdatesError': 'Não foi possível verificar atualizações',
        'ytDlpUpdating': 'Aguarde, atualizando bibliotecas internas...',
        'ytDlpUpdateDone': 'Bibliotecas internas atualizadas',
        'installFailedMsg': 'Não foi possível instalar as bibliotecas internas, então {appName} será fechado agora. Execute-o novamente para tentar de novo.',
        'btnClose': 'Fechar',
        'setupCompleteMsg': 'Tudo pronto, você pode começar!',
        'confirmExitTitle': 'Confirmar saída',
        'confirmExitMsg': 'Um download está em andamento. Tem certeza de que deseja sair? Ele será interrompido.',
        'restartRequired': 'Reinicie o {appName} para que as alterações tenham efeito.',
        'titleError': 'Erro',
        'titleUpdates': 'Atualizações',
        'titleRestart': 'Reinicialização necessária',
        'msgContentCopied': 'Conteúdo copiado',
        'msgFoundLinks': '%s links válidos encontrados',
        'msgNoValidLinks': 'Nenhum link válido encontrado',
        'msgInvalidPastylink': 'O link foi copiado incorretamente, volte ao Pastylink e tente novamente',
        'msgDownloadStarted': 'Download iniciado...',
        'msgDownloadFinished': 'Download concluído em %s segundos',
        'typeDownload': 'Download',
        'typeConversion': 'Conversão',
        'msgInProgress': ' em andamento para o item n.º %s',
        'colUrl': 'Url',
        'colState': 'Estado',
        'colStatusCode': 'CódigoEstado',
        'colSaveAs': 'SalvarComo',
        'colActions': 'Ações',
        'ctxCopyLink': 'Copiar endereço do link',
        'ctxOpenFolder': 'Abrir pasta de download',
        'ctxDownloadNow': 'Baixar agora',
        'ctxConvertMp3': 'Converter para mp3',
        'ctxStop': 'Parar',
        'ctxRemove': 'Remover',
        'ctxDeleteAndRemove': 'Excluir arquivo e remover',
        'menuFile': 'Arquivo',
        'menuEdit': 'Editar',
        'menuHelp': 'Ajuda',
        'actionExit': 'Sair',
        'actionStartWaiting': 'Iniciar links em espera',
        'actionStopAll': 'Parar tudo',
        'actionRemoveAll': 'Remover tudo',
        'actionPreferences': 'Preferências',
        'actionCheckUpdates': 'Verificar atualizações',
        'actionAbout': 'Sobre',
        'prefsTitle': 'Preferências',
        'downloadFolderLabel': 'Pasta de Download',
        'selectButton': 'Selecionar',
        'videoGroupLabel': 'Vídeo',
        'convNever': 'Nunca converter',
        'convDeleteVideo': 'Sempre converter para áudio e excluir o vídeo',
        'convKeepVideo': 'Sempre converter para áudio e manter o vídeo',
        'afterDownloadLabel': 'Após o download',
        'doOpenFolder': 'Abrir a pasta de downloads',
        'doNothing': 'Não fazer nada',
        'languageLabel': 'Idioma',
        'themeLabel': 'Tema',
        'themeSystem': 'Sistema (padrão)',
        'themeLight': 'Claro',
        'themeDark': 'Escuro',
    },

    # russo
    'ru': {
        'aboutVersion': 'Версия: %s',
        'aboutWebsite': 'Сайт: {website}',
        'aboutPrivacy': 'Конфиденциальность: мы анонимно собираем версию приложения и операционную систему для агрегированной статистики использования.',
        'btnDefault': ' Вставить и скачать',
        'btnReverse': ' Подождите...',
        'downloadPathError': 'Папка загрузки недоступна',
        'internetError': 'Нет подключения к интернету, возможно оно заблокировано антивирусом или брандмауэром',
        'noLinks': 'Нет ссылок, ожидающих загрузки',
        'txtUpdatesHtml': 'Доступна новая версия <br><b>%s</b><br>!<br><br>Перейдите на {website}<br>',
        'txtUpdatesTxt': 'Доступна новая версия %s!',
        'txtUpdatesNo': '{appName} уже обновлён<br>',
        'txtUpdatesError': 'Не удалось проверить обновления',
        'ytDlpUpdating': 'Подождите, обновление внутренних библиотек...',
        'ytDlpUpdateDone': 'Внутренние библиотеки обновлены',
        'installFailedMsg': 'Не удалось установить внутренние библиотеки, поэтому {appName} сейчас закроется. Запустите приложение снова, чтобы повторить попытку.',
        'btnClose': 'Закрыть',
        'setupCompleteMsg': 'Всё готово, можно начинать!',
        'confirmExitTitle': 'Подтвердите выход',
        'confirmExitMsg': 'Выполняется загрузка. Вы уверены, что хотите выйти? Она будет остановлена.',
        'restartRequired': 'Перезапустите {appName}, чтобы изменения вступили в силу.',
        'titleError': 'Ошибка',
        'titleUpdates': 'Обновления',
        'titleRestart': 'Требуется перезапуск',
        'msgContentCopied': 'Содержимое скопировано',
        'msgFoundLinks': 'Найдено %s действительных ссылок',
        'msgNoValidLinks': 'Действительных ссылок не найдено',
        'msgInvalidPastylink': 'Ссылка скопирована неправильно, вернитесь в Pastylink и попробуйте снова',
        'msgDownloadStarted': 'Загрузка начата...',
        'msgDownloadFinished': 'Загрузка завершена за %s секунд',
        'typeDownload': 'Загрузка',
        'typeConversion': 'Конвертация',
        'msgInProgress': ' выполняется для элемента № %s',
        'colUrl': 'Url',
        'colState': 'Статус',
        'colStatusCode': 'КодСтатуса',
        'colSaveAs': 'СохранитьКак',
        'colActions': 'Действия',
        'ctxCopyLink': 'Копировать адрес ссылки',
        'ctxOpenFolder': 'Открыть папку загрузки',
        'ctxDownloadNow': 'Скачать сейчас',
        'ctxConvertMp3': 'Конвертировать в mp3',
        'ctxStop': 'Остановить',
        'ctxRemove': 'Удалить',
        'ctxDeleteAndRemove': 'Удалить файл и убрать из списка',
        'menuFile': 'Файл',
        'menuEdit': 'Правка',
        'menuHelp': 'Справка',
        'actionExit': 'Выход',
        'actionStartWaiting': 'Запустить ожидающие ссылки',
        'actionStopAll': 'Остановить всё',
        'actionRemoveAll': 'Удалить всё',
        'actionPreferences': 'Настройки',
        'actionCheckUpdates': 'Проверить обновления',
        'actionAbout': 'О программе',
        'prefsTitle': 'Настройки',
        'downloadFolderLabel': 'Папка загрузки',
        'selectButton': 'Выбрать',
        'videoGroupLabel': 'Видео',
        'convNever': 'Никогда не конвертировать',
        'convDeleteVideo': 'Всегда конвертировать в аудио и удалять видео',
        'convKeepVideo': 'Всегда конвертировать в аудио и сохранять видео',
        'afterDownloadLabel': 'После загрузки',
        'doOpenFolder': 'Открыть папку загрузок',
        'doNothing': 'Ничего не делать',
        'languageLabel': 'Язык',
        'themeLabel': 'Тема',
        'themeSystem': 'Системная (по умолчанию)',
        'themeLight': 'Светлая',
        'themeDark': 'Тёмная',
    },

    # coreano
    'ko': {
        'aboutVersion': '버전: %s',
        'aboutWebsite': '웹사이트: {website}',
        'aboutPrivacy': '개인정보: 집계된 사용 통계를 위해 앱 버전과 운영체제를 익명으로 수집합니다.',
        'btnDefault': ' 붙여넣고 다운로드',
        'btnReverse': ' 잠시만 기다려 주세요...',
        'downloadPathError': '다운로드 폴더에 접근할 수 없습니다',
        'internetError': '인터넷 연결이 없습니다. 백신 프로그램이나 방화벽에 의해 차단되었을 수 있습니다',
        'noLinks': '다운로드를 기다리는 링크가 없습니다',
        'txtUpdatesHtml': '새 버전 <br><b>%s</b><br> 을(를) 사용할 수 있습니다!<br><br>{website} 로 이동하세요<br>',
        'txtUpdatesTxt': '새 버전 %s을(를) 사용할 수 있습니다!',
        'txtUpdatesNo': '{appName}이(가) 이미 최신 버전입니다<br>',
        'txtUpdatesError': '업데이트를 확인할 수 없습니다',
        'ytDlpUpdating': '잠시만 기다려 주세요, 내부 라이브러리를 업데이트하는 중...',
        'ytDlpUpdateDone': '내부 라이브러리가 업데이트되었습니다',
        'installFailedMsg': '내부 라이브러리를 설치하지 못해 {appName}이(가) 곧 종료됩니다. 다시 실행하여 재시도하세요.',
        'btnClose': '닫기',
        'setupCompleteMsg': '준비 완료, 시작할 수 있습니다!',
        'confirmExitTitle': '종료 확인',
        'confirmExitMsg': '다운로드가 진행 중입니다. 정말 종료하시겠습니까? 다운로드가 중단됩니다.',
        'restartRequired': '변경 사항을 적용하려면 {appName}을(를) 다시 시작하세요.',
        'titleError': '오류',
        'titleUpdates': '업데이트',
        'titleRestart': '재시작 필요',
        'msgContentCopied': '내용이 복사되었습니다',
        'msgFoundLinks': '유효한 링크 %s개를 찾았습니다',
        'msgNoValidLinks': '유효한 링크를 찾을 수 없습니다',
        'msgInvalidPastylink': '링크가 잘못 복사되었습니다. Pastylink로 돌아가서 다시 시도하세요',
        'msgDownloadStarted': '다운로드가 시작되었습니다...',
        'msgDownloadFinished': '%s초 만에 다운로드가 완료되었습니다',
        'typeDownload': '다운로드',
        'typeConversion': '변환',
        'msgInProgress': ' 항목 번호 %s 처리 중',
        'colUrl': 'Url',
        'colState': '상태',
        'colStatusCode': '상태코드',
        'colSaveAs': '저장위치',
        'colActions': '작업',
        'ctxCopyLink': '링크 주소 복사',
        'ctxOpenFolder': '다운로드 폴더 열기',
        'ctxDownloadNow': '지금 다운로드',
        'ctxConvertMp3': 'mp3로 변환',
        'ctxStop': '중지',
        'ctxRemove': '제거',
        'ctxDeleteAndRemove': '파일 삭제 및 제거',
        'menuFile': '파일',
        'menuEdit': '편집',
        'menuHelp': '도움말',
        'actionExit': '종료',
        'actionStartWaiting': '대기 중인 링크 시작',
        'actionStopAll': '모두 중지',
        'actionRemoveAll': '모두 제거',
        'actionPreferences': '환경설정',
        'actionCheckUpdates': '업데이트 확인',
        'actionAbout': '정보',
        'prefsTitle': '환경설정',
        'downloadFolderLabel': '다운로드 폴더',
        'selectButton': '선택',
        'videoGroupLabel': '비디오',
        'convNever': '변환하지 않음',
        'convDeleteVideo': '항상 오디오로 변환하고 비디오 삭제',
        'convKeepVideo': '항상 오디오로 변환하고 비디오 유지',
        'afterDownloadLabel': '다운로드 후',
        'doOpenFolder': '다운로드 폴더 열기',
        'doNothing': '아무 작업도 하지 않음',
        'languageLabel': '언어',
        'themeLabel': '테마',
        'themeSystem': '시스템(기본값)',
        'themeLight': '라이트',
        'themeDark': '다크',
    },

    # olandese
    'nl': {
        'aboutVersion': 'Versie: %s',
        'aboutWebsite': 'Website: {website}',
        'aboutPrivacy': 'Privacy: we verzamelen anoniem de app-versie en het besturingssysteem voor geaggregeerde gebruiksstatistieken.',
        'btnDefault': ' Plakken en Downloaden',
        'btnReverse': ' Even geduld...',
        'downloadPathError': 'De downloadmap is niet toegankelijk',
        'internetError': 'Er is geen internetverbinding, deze kan geblokkeerd zijn door de antivirus of firewall',
        'noLinks': 'Er zijn geen links die wachten op download',
        'txtUpdatesHtml': 'De nieuwe versie <br><b>%s</b><br> is beschikbaar!<br><br>Ga naar {website}<br>',
        'txtUpdatesTxt': 'Nieuwe versie %s beschikbaar!',
        'txtUpdatesNo': '{appName} is al bijgewerkt<br>',
        'txtUpdatesError': 'Kan niet controleren op updates',
        'ytDlpUpdating': 'Even geduld, interne bibliotheken worden bijgewerkt...',
        'ytDlpUpdateDone': 'Interne bibliotheken bijgewerkt',
        'installFailedMsg': 'Interne bibliotheken konden niet worden geïnstalleerd, dus {appName} wordt nu afgesloten. Start het opnieuw om het nogmaals te proberen.',
        'btnClose': 'Sluiten',
        'setupCompleteMsg': 'Helemaal klaar, je kunt beginnen!',
        'confirmExitTitle': 'Afsluiten bevestigen',
        'confirmExitMsg': 'Er is een download bezig. Weet je zeker dat je wilt afsluiten? Deze wordt gestopt.',
        'restartRequired': 'Start {appName} opnieuw op zodat de wijzigingen van kracht worden.',
        'titleError': 'Fout',
        'titleUpdates': 'Updates',
        'titleRestart': 'Opnieuw opstarten vereist',
        'msgContentCopied': 'Inhoud gekopieerd',
        'msgFoundLinks': '%s geldige links gevonden',
        'msgNoValidLinks': 'Geen geldige link gevonden',
        'msgInvalidPastylink': 'De link is verkeerd gekopieerd, ga terug naar Pastylink en probeer het opnieuw',
        'msgDownloadStarted': 'Download gestart...',
        'msgDownloadFinished': 'Download voltooid in %s seconden',
        'typeDownload': 'Download',
        'typeConversion': 'Conversie',
        'msgInProgress': ' bezig voor item nr. %s',
        'colUrl': 'Url',
        'colState': 'Status',
        'colStatusCode': 'Statuscode',
        'colSaveAs': 'OpslaanAls',
        'colActions': 'Acties',
        'ctxCopyLink': 'Linkadres kopiëren',
        'ctxOpenFolder': 'Downloadmap openen',
        'ctxDownloadNow': 'Nu downloaden',
        'ctxConvertMp3': 'Converteren naar mp3',
        'ctxStop': 'Stoppen',
        'ctxRemove': 'Verwijderen',
        'ctxDeleteAndRemove': 'Bestand verwijderen en uit lijst halen',
        'menuFile': 'Bestand',
        'menuEdit': 'Bewerken',
        'menuHelp': 'Help',
        'actionExit': 'Afsluiten',
        'actionStartWaiting': 'Wachtende links starten',
        'actionStopAll': 'Alles stoppen',
        'actionRemoveAll': 'Alles verwijderen',
        'actionPreferences': 'Voorkeuren',
        'actionCheckUpdates': 'Controleren op updates',
        'actionAbout': 'Over',
        'prefsTitle': 'Voorkeuren',
        'downloadFolderLabel': 'Downloadmap',
        'selectButton': 'Selecteren',
        'videoGroupLabel': 'Video',
        'convNever': 'Nooit converteren',
        'convDeleteVideo': 'Altijd converteren naar audio en video verwijderen',
        'convKeepVideo': 'Altijd converteren naar audio en video behouden',
        'afterDownloadLabel': 'Na het downloaden',
        'doOpenFolder': 'De downloadmap openen',
        'doNothing': 'Niets doen',
        'languageLabel': 'Taal',
        'themeLabel': 'Thema',
        'themeSystem': 'Systeem (standaard)',
        'themeLight': 'Licht',
        'themeDark': 'Donker',
    },

    # arabo
    'ar': {
        'aboutVersion': 'الإصدار: %s',
        'aboutWebsite': 'الموقع: {website}',
        'aboutPrivacy': 'الخصوصية: نجمع إصدار التطبيق ونظام التشغيل بشكل مجهول لأغراض إحصاءات الاستخدام المجمعة.',
        'btnDefault': ' الصق وقم بالتنزيل',
        'btnReverse': ' يرجى الانتظار...',
        'downloadPathError': 'تعذّر الوصول إلى مجلد التنزيل',
        'internetError': 'لا يوجد اتصال بالإنترنت، قد يكون محظورًا بواسطة مضاد الفيروسات أو جدار الحماية',
        'noLinks': 'لا توجد روابط بانتظار التنزيل',
        'txtUpdatesHtml': 'الإصدار الجديد <br><b>%s</b><br> متاح الآن!<br><br>انتقل إلى {website}<br>',
        'txtUpdatesTxt': 'الإصدار الجديد %s متاح الآن!',
        'txtUpdatesNo': '{appName} محدّث بالفعل<br>',
        'txtUpdatesError': 'تعذّر التحقق من وجود تحديثات',
        'ytDlpUpdating': 'يرجى الانتظار، جارٍ تحديث المكتبات الداخلية...',
        'ytDlpUpdateDone': 'تم تحديث المكتبات الداخلية',
        'installFailedMsg': 'تعذّر تثبيت المكتبات الداخلية، لذا سيتم إغلاق {appName} الآن. أعد تشغيله للمحاولة مرة أخرى.',
        'btnClose': 'إغلاق',
        'setupCompleteMsg': 'اكتمل كل شيء، يمكنك البدء الآن!',
        'confirmExitTitle': 'تأكيد الخروج',
        'confirmExitMsg': 'هناك عملية تنزيل جارية. هل تريد الخروج فعلاً؟ سيتم إيقافها.',
        'restartRequired': 'أعد تشغيل {appName} لتفعيل التغييرات.',
        'titleError': 'خطأ',
        'titleUpdates': 'التحديثات',
        'titleRestart': 'إعادة التشغيل مطلوبة',
        'msgContentCopied': 'تم نسخ المحتوى',
        'msgFoundLinks': 'تم العثور على %s روابط صالحة',
        'msgNoValidLinks': 'لم يتم العثور على أي رابط صالح',
        'msgInvalidPastylink': 'تم نسخ الرابط بشكل غير صحيح، عد إلى Pastylink وحاول مرة أخرى',
        'msgDownloadStarted': 'بدأ التنزيل...',
        'msgDownloadFinished': 'اكتمل التنزيل خلال %s ثانية',
        'typeDownload': 'تنزيل',
        'typeConversion': 'تحويل',
        'msgInProgress': ' قيد التنفيذ للعنصر رقم %s',
        'colUrl': 'الرابط',
        'colState': 'الحالة',
        'colStatusCode': 'رمز الحالة',
        'colSaveAs': 'الحفظ باسم',
        'colActions': 'إجراءات',
        'ctxCopyLink': 'نسخ عنوان الرابط',
        'ctxOpenFolder': 'فتح مجلد التنزيل',
        'ctxDownloadNow': 'تنزيل الآن',
        'ctxConvertMp3': 'تحويل إلى mp3',
        'ctxStop': 'إيقاف',
        'ctxRemove': 'إزالة',
        'ctxDeleteAndRemove': 'حذف الملف وإزالته',
        'menuFile': 'ملف',
        'menuEdit': 'تحرير',
        'menuHelp': 'مساعدة',
        'actionExit': 'خروج',
        'actionStartWaiting': 'بدء الروابط المنتظرة',
        'actionStopAll': 'إيقاف الكل',
        'actionRemoveAll': 'إزالة الكل',
        'actionPreferences': 'التفضيلات',
        'actionCheckUpdates': 'التحقق من التحديثات',
        'actionAbout': 'حول',
        'prefsTitle': 'التفضيلات',
        'downloadFolderLabel': 'مجلد التنزيل',
        'selectButton': 'اختيار',
        'videoGroupLabel': 'فيديو',
        'convNever': 'عدم التحويل أبدًا',
        'convDeleteVideo': 'التحويل دائمًا إلى صوت وحذف الفيديو',
        'convKeepVideo': 'التحويل دائمًا إلى صوت والاحتفاظ بالفيديو',
        'afterDownloadLabel': 'بعد التنزيل',
        'doOpenFolder': 'فتح مجلد التنزيلات',
        'doNothing': 'عدم القيام بأي شيء',
        'languageLabel': 'اللغة',
        'themeLabel': 'المظهر',
        'themeSystem': 'النظام (افتراضي)',
        'themeLight': 'فاتح',
        'themeDark': 'داكن',
    },
}


class MyText():

    # api
    referers = 'https://pasty.info/other/pasty_downloader/api/referer.json'
    checkUpdates = 'https://pasty.info/other/pasty_downloader/api/checkUpdates/'
    saveStats = 'https://pasty.info/other/pasty_downloader/api/saveStats/'

    # info
    appName = 'PastyDownloader'
    orgName = 'Pastylink'
    orgDomain = 'pasty.link'
    website = '<a href="https://pasty.link">pasty.link</a>'

    # files
    pasty_icon = ':/images/paste.png'
    pasty_icon_rev = ':/images/paste_revert.png'
    pasty_favicon = ':/images/favicon.ico'

    LANGUAGES = sorted([
        ('en', 'English'), ('it', 'Italiano'), ('fr', 'Français'),
        ('es', 'Español'), ('de', 'Deutsch'), ('zh', '简体中文'), ('ja', '日本語'),
        ('pt', 'Português'), ('ru', 'Русский'), ('ko', '한국어'),
        ('nl', 'Nederlands'), ('ar', 'العربية'),
    ], key=lambda pair: pair[1])
    DEFAULT_LANGUAGE = 'en'

    @classmethod
    def getLanguage(cls):
        settings = QSettings(cls.orgName, cls.appName)
        lang = settings.value('language')
        if lang in _TRANSLATIONS:
            return lang
        # nessuna lingua mai scelta (primo avvio): usa quella del sistema
        # operativo se supportata, altrimenti l'inglese - e la salva subito,
        # cosi' non viene ridetectata a ogni avvio (settings.value('language')
        # non sara' piu' vuoto) e un'eventuale scelta manuale in Preferenze la
        # sovrascrive normalmente tramite setLanguage()
        detected = QLocale.system().name().split('_')[0]
        chosen = detected if detected in _TRANSLATIONS else cls.DEFAULT_LANGUAGE
        settings.setValue('language', chosen)
        return chosen

    @classmethod
    def setLanguage(cls, lang):
        QSettings(cls.orgName, cls.appName).setValue('language', lang)
        cls._loadLanguage(lang)

    @classmethod
    def _loadLanguage(cls, lang):
        strings = _TRANSLATIONS.get(lang, _TRANSLATIONS[cls.DEFAULT_LANGUAGE])
        for key, value in strings.items():
            setattr(cls, key, value.format(website=cls.website, appName=cls.appName))


MyText._loadLanguage(MyText.getLanguage())
