#!/usr/bin/python

from PySide6.QtCore import QSettings

# Ogni voce qui sotto e' un testo visibile in UI e va tradotta in tutte le lingue.
# {website} e {appName} vengono sostituiti automaticamente dopo il caricamento.
_TRANSLATIONS = {

    # inglese
    'en': {
        'aboutVersion': 'Version: %s',
        'aboutWebsite': 'Website: {website}',
        'btnDefault': ' Paste and Download',
        'btnReverse': ' Please wait...',
        'ffmpegRequired': 'FFmpeg is required to run {appName}.<br>Download it by visiting the website <a href="https://ffmpeg.org/">https://ffmpeg.org/</a>',
        'downloadPathError': 'The download folder is not accessible',
        'internetError': 'There is no internet connection, it may be blocked by the antivirus or firewall',
        'noLinks': 'There are no links waiting for download',
        'txtUpdatesHtml': 'The new version <br><b>%s</b><br> is available!<br><br>Go to {website}<br>',
        'txtUpdatesTxt': 'New version %s available!',
        'txtUpdatesNo': '{appName} is already updated<br>',
        'txtUpdatesError': 'Unable to check for updates',
        'ytDlpUpdating': 'Updating internal libraries...',
        'ytDlpUpdateDone': 'Internal libraries updated',
        'confirmExitTitle': 'Confirm exit',
        'confirmExitMsg': 'A download is in progress. Are you sure you want to exit? It will be stopped.',
        'restartRequired': 'Restart {appName} for the language change to take effect.',
        'titleRequirements': 'Requirements',
        'titleError': 'Error',
        'titleUpdates': 'Updates',
        'titleRestart': 'Restart required',
        'msgContentCopied': 'Content is copied',
        'msgFoundLinks': 'Found %s valid links',
        'msgNoValidLinks': 'No valid links found',
        'msgInvalidPastylink': 'The link was copied incorrectly, go back to Pastylink and try again',
        'msgDownloadStarted': 'Download started...',
        'msgDownloadFinished': 'Download finished in %s seconds',
        'typeDownload': 'Download',
        'typeConversion': 'Conversion',
        'msgInProgress': ' in progress for item no. %s',
        'colUrl': 'Url',
        'colState': 'State',
        'colStatusCode': 'StatusCode',
        'colSaveAs': 'SaveAs',
        'colActions': 'Actions',
        'ctxCopyLink': 'Copy link address',
        'ctxOpenFolder': 'Open download folder',
        'ctxDownloadNow': 'Download now',
        'ctxConvertMp3': 'Convert to mp3 audio',
        'ctxStop': 'Stop',
        'ctxRemove': 'Remove',
        'ctxDeleteAndRemove': 'Delete file and Remove',
        'menuFile': 'File',
        'menuEdit': 'Edit',
        'menuHelp': 'Help',
        'actionExit': 'Exit',
        'actionStartWaiting': 'Start waiting links',
        'actionStopAll': 'Stop All',
        'actionRemoveAll': 'Remove all',
        'actionPreferences': 'Preferences',
        'actionCheckUpdates': 'Check for updates',
        'actionAbout': 'About',
        'prefsTitle': 'Preferences',
        'downloadFolderLabel': 'Download Folder',
        'selectButton': 'Select',
        'videoGroupLabel': 'Video',
        'convNever': 'Never convert',
        'convDeleteVideo': 'Convert always to audio and delete video',
        'convKeepVideo': 'Convert always to audio and keep video',
        'afterDownloadLabel': 'After download',
        'doOpenFolder': 'Open the downloads folder',
        'doNothing': 'Do nothing',
        'languageLabel': 'Language',
    },

    # italiano
    'it': {
        'aboutVersion': 'Versione: %s',
        'aboutWebsite': 'Sito: {website}',
        'btnDefault': ' Incolla e Scarica',
        'btnReverse': ' Attendere...',
        'ffmpegRequired': 'FFmpeg è necessario per eseguire {appName}.<br>Scaricalo visitando il sito <a href="https://ffmpeg.org/">https://ffmpeg.org/</a>',
        'downloadPathError': 'La cartella di download non è accessibile',
        'internetError': "Non c'è connessione a internet, potrebbe essere bloccata dall'antivirus o dal firewall",
        'noLinks': 'Non ci sono link in attesa di download',
        'txtUpdatesHtml': 'La nuova versione <br><b>%s</b><br> è disponibile!<br><br>Vai su {website}<br>',
        'txtUpdatesTxt': 'Nuova versione %s disponibile!',
        'txtUpdatesNo': '{appName} è già aggiornato<br>',
        'txtUpdatesError': 'Impossibile verificare gli aggiornamenti',
        'ytDlpUpdating': 'Aggiornamento delle librerie interne in corso...',
        'ytDlpUpdateDone': 'Librerie interne aggiornate',
        'confirmExitTitle': 'Conferma uscita',
        'confirmExitMsg': 'È in corso un download. Sei sicuro di voler uscire? Verrà interrotto.',
        'restartRequired': 'Riavvia {appName} perché il cambio lingua abbia effetto.',
        'titleRequirements': 'Requisiti',
        'titleError': 'Errore',
        'titleUpdates': 'Aggiornamenti',
        'titleRestart': 'Riavvio necessario',
        'msgContentCopied': 'Contenuto copiato',
        'msgFoundLinks': 'Trovati %s link validi',
        'msgNoValidLinks': 'Nessun link valido trovato',
        'msgInvalidPastylink': 'Il link è stato copiato male, torna su Pastylink e riprova',
        'msgDownloadStarted': 'Download avviato...',
        'msgDownloadFinished': 'Download completato in %s secondi',
        'typeDownload': 'Download',
        'typeConversion': 'Conversione',
        'msgInProgress': " in corso per l'elemento n. %s",
        'colUrl': 'Url',
        'colState': 'Stato',
        'colStatusCode': 'CodiceStato',
        'colSaveAs': 'SalvaCome',
        'colActions': 'Azioni',
        'ctxCopyLink': 'Copia indirizzo link',
        'ctxOpenFolder': 'Apri cartella di download',
        'ctxDownloadNow': 'Scarica ora',
        'ctxConvertMp3': 'Converti in mp3',
        'ctxStop': 'Ferma',
        'ctxRemove': 'Rimuovi',
        'ctxDeleteAndRemove': 'Elimina file e rimuovi',
        'menuFile': 'File',
        'menuEdit': 'Modifica',
        'menuHelp': 'Aiuto',
        'actionExit': 'Esci',
        'actionStartWaiting': 'Avvia link in attesa',
        'actionStopAll': 'Ferma tutto',
        'actionRemoveAll': 'Rimuovi tutto',
        'actionPreferences': 'Preferenze',
        'actionCheckUpdates': 'Controlla aggiornamenti',
        'actionAbout': 'Informazioni',
        'prefsTitle': 'Preferenze',
        'downloadFolderLabel': 'Cartella di Download',
        'selectButton': 'Seleziona',
        'videoGroupLabel': 'Video',
        'convNever': 'Non convertire mai',
        'convDeleteVideo': "Converti sempre in audio ed elimina il video",
        'convKeepVideo': 'Converti sempre in audio e mantieni il video',
        'afterDownloadLabel': 'Dopo il download',
        'doOpenFolder': 'Apri la cartella dei download',
        'doNothing': 'Non fare nulla',
        'languageLabel': 'Lingua',
    },

    # francese
    'fr': {
        'aboutVersion': 'Version : %s',
        'aboutWebsite': 'Site : {website}',
        'btnDefault': ' Coller et Télécharger',
        'btnReverse': ' Veuillez patienter...',
        'ffmpegRequired': 'FFmpeg est requis pour exécuter {appName}.<br>Téléchargez-le en visitant le site <a href="https://ffmpeg.org/">https://ffmpeg.org/</a>',
        'downloadPathError': "Le dossier de téléchargement n'est pas accessible",
        'internetError': "Il n'y a pas de connexion internet, elle est peut-être bloquée par l'antivirus ou le pare-feu",
        'noLinks': "Il n'y a aucun lien en attente de téléchargement",
        'txtUpdatesHtml': 'La nouvelle version <br><b>%s</b><br> est disponible !<br><br>Allez sur {website}<br>',
        'txtUpdatesTxt': 'Nouvelle version %s disponible !',
        'txtUpdatesNo': '{appName} est déjà à jour<br>',
        'txtUpdatesError': 'Impossible de vérifier les mises à jour',
        'ytDlpUpdating': 'Mise à jour des bibliothèques internes...',
        'ytDlpUpdateDone': 'Bibliothèques internes mises à jour',
        'confirmExitTitle': 'Confirmer la fermeture',
        'confirmExitMsg': 'Un téléchargement est en cours. Voulez-vous vraiment quitter ? Il sera interrompu.',
        'restartRequired': 'Redémarrez {appName} pour que le changement de langue prenne effet.',
        'titleRequirements': 'Prérequis',
        'titleError': 'Erreur',
        'titleUpdates': 'Mises à jour',
        'titleRestart': 'Redémarrage requis',
        'msgContentCopied': 'Contenu copié',
        'msgFoundLinks': '%s liens valides trouvés',
        'msgNoValidLinks': 'Aucun lien valide trouvé',
        'msgInvalidPastylink': 'Le lien a été copié incorrectement, retournez sur Pastylink et réessayez',
        'msgDownloadStarted': 'Téléchargement démarré...',
        'msgDownloadFinished': 'Téléchargement terminé en %s secondes',
        'typeDownload': 'Téléchargement',
        'typeConversion': 'Conversion',
        'msgInProgress': " en cours pour l'élément n° %s",
        'colUrl': 'Url',
        'colState': 'État',
        'colStatusCode': 'CodeÉtat',
        'colSaveAs': 'Enregistré',
        'colActions': 'Actions',
        'ctxCopyLink': "Copier l'adresse du lien",
        'ctxOpenFolder': 'Ouvrir le dossier de téléchargement',
        'ctxDownloadNow': 'Télécharger maintenant',
        'ctxConvertMp3': 'Convertir en mp3',
        'ctxStop': 'Arrêter',
        'ctxRemove': 'Supprimer',
        'ctxDeleteAndRemove': 'Supprimer le fichier et la ligne',
        'menuFile': 'Fichier',
        'menuEdit': 'Édition',
        'menuHelp': 'Aide',
        'actionExit': 'Quitter',
        'actionStartWaiting': 'Démarrer les liens en attente',
        'actionStopAll': 'Tout arrêter',
        'actionRemoveAll': 'Tout supprimer',
        'actionPreferences': 'Préférences',
        'actionCheckUpdates': 'Vérifier les mises à jour',
        'actionAbout': 'À propos',
        'prefsTitle': 'Préférences',
        'downloadFolderLabel': 'Dossier de téléchargement',
        'selectButton': 'Sélectionner',
        'videoGroupLabel': 'Vidéo',
        'convNever': 'Ne jamais convertir',
        'convDeleteVideo': 'Toujours convertir en audio et supprimer la vidéo',
        'convKeepVideo': 'Toujours convertir en audio et conserver la vidéo',
        'afterDownloadLabel': 'Après le téléchargement',
        'doOpenFolder': 'Ouvrir le dossier de téléchargements',
        'doNothing': 'Ne rien faire',
        'languageLabel': 'Langue',
    },

    # spagnolo
    'es': {
        'aboutVersion': 'Versión: %s',
        'aboutWebsite': 'Web: {website}',
        'btnDefault': ' Pegar y Descargar',
        'btnReverse': ' Espere por favor...',
        'ffmpegRequired': 'FFmpeg es necesario para ejecutar {appName}.<br>Descárgalo visitando el sitio <a href="https://ffmpeg.org/">https://ffmpeg.org/</a>',
        'downloadPathError': 'La carpeta de descarga no es accesible',
        'internetError': 'No hay conexión a internet, puede estar bloqueada por el antivirus o el firewall',
        'noLinks': 'No hay enlaces esperando para descargar',
        'txtUpdatesHtml': 'La nueva versión <br><b>%s</b><br> está disponible!<br><br>Ve a {website}<br>',
        'txtUpdatesTxt': '¡Nueva versión %s disponible!',
        'txtUpdatesNo': '{appName} ya está actualizado<br>',
        'txtUpdatesError': 'No se pueden comprobar actualizaciones',
        'ytDlpUpdating': 'Actualizando las librerías internas...',
        'ytDlpUpdateDone': 'Librerías internas actualizadas',
        'confirmExitTitle': 'Confirmar salida',
        'confirmExitMsg': 'Hay una descarga en curso. ¿Seguro que quieres salir? Se detendrá.',
        'restartRequired': 'Reinicia {appName} para que el cambio de idioma tenga efecto.',
        'titleRequirements': 'Requisitos',
        'titleError': 'Error',
        'titleUpdates': 'Actualizaciones',
        'titleRestart': 'Reinicio necesario',
        'msgContentCopied': 'Contenido copiado',
        'msgFoundLinks': 'Se encontraron %s enlaces válidos',
        'msgNoValidLinks': 'No se encontró ningún enlace válido',
        'msgInvalidPastylink': 'El enlace se copió incorrectamente, vuelve a Pastylink e inténtalo de nuevo',
        'msgDownloadStarted': 'Descarga iniciada...',
        'msgDownloadFinished': 'Descarga completada en %s segundos',
        'typeDownload': 'Descarga',
        'typeConversion': 'Conversión',
        'msgInProgress': ' en curso para el elemento n.º %s',
        'colUrl': 'Url',
        'colState': 'Estado',
        'colStatusCode': 'CódigoEstado',
        'colSaveAs': 'GuardarComo',
        'colActions': 'Acciones',
        'ctxCopyLink': 'Copiar dirección del enlace',
        'ctxOpenFolder': 'Abrir carpeta de descarga',
        'ctxDownloadNow': 'Descargar ahora',
        'ctxConvertMp3': 'Convertir a mp3',
        'ctxStop': 'Detener',
        'ctxRemove': 'Eliminar',
        'ctxDeleteAndRemove': 'Eliminar archivo y quitar',
        'menuFile': 'Archivo',
        'menuEdit': 'Editar',
        'menuHelp': 'Ayuda',
        'actionExit': 'Salir',
        'actionStartWaiting': 'Iniciar enlaces en espera',
        'actionStopAll': 'Detener todo',
        'actionRemoveAll': 'Eliminar todo',
        'actionPreferences': 'Preferencias',
        'actionCheckUpdates': 'Buscar actualizaciones',
        'actionAbout': 'Acerca de',
        'prefsTitle': 'Preferencias',
        'downloadFolderLabel': 'Carpeta de Descarga',
        'selectButton': 'Seleccionar',
        'videoGroupLabel': 'Vídeo',
        'convNever': 'No convertir nunca',
        'convDeleteVideo': 'Convertir siempre a audio y eliminar el vídeo',
        'convKeepVideo': 'Convertir siempre a audio y mantener el vídeo',
        'afterDownloadLabel': 'Después de la descarga',
        'doOpenFolder': 'Abrir la carpeta de descargas',
        'doNothing': 'No hacer nada',
        'languageLabel': 'Idioma',
    },

    # tedesco
    'de': {
        'aboutVersion': 'Version: %s',
        'aboutWebsite': 'Webseite: {website}',
        'btnDefault': ' Einfügen und Herunterladen',
        'btnReverse': ' Bitte warten...',
        'ffmpegRequired': 'FFmpeg wird benötigt, um {appName} auszuführen.<br>Lade es herunter auf <a href="https://ffmpeg.org/">https://ffmpeg.org/</a>',
        'downloadPathError': 'Der Download-Ordner ist nicht zugänglich',
        'internetError': 'Keine Internetverbindung, sie könnte von Antivirus oder Firewall blockiert sein',
        'noLinks': 'Es gibt keine Links, die auf den Download warten',
        'txtUpdatesHtml': 'Die neue Version <br><b>%s</b><br> ist verfügbar!<br><br>Gehe zu {website}<br>',
        'txtUpdatesTxt': 'Neue Version %s verfügbar!',
        'txtUpdatesNo': '{appName} ist bereits aktuell<br>',
        'txtUpdatesError': 'Updates konnten nicht überprüft werden',
        'ytDlpUpdating': 'Interne Bibliotheken werden aktualisiert...',
        'ytDlpUpdateDone': 'Interne Bibliotheken aktualisiert',
        'confirmExitTitle': 'Beenden bestätigen',
        'confirmExitMsg': 'Ein Download läuft gerade. Möchtest du wirklich beenden? Er wird abgebrochen.',
        'restartRequired': 'Starte {appName} neu, damit die Sprachänderung wirksam wird.',
        'titleRequirements': 'Voraussetzungen',
        'titleError': 'Fehler',
        'titleUpdates': 'Updates',
        'titleRestart': 'Neustart erforderlich',
        'msgContentCopied': 'Inhalt kopiert',
        'msgFoundLinks': '%s gültige Links gefunden',
        'msgNoValidLinks': 'Kein gültiger Link gefunden',
        'msgInvalidPastylink': 'Der Link wurde falsch kopiert, gehe zurück zu Pastylink und versuche es erneut',
        'msgDownloadStarted': 'Download gestartet...',
        'msgDownloadFinished': 'Download in %s Sekunden abgeschlossen',
        'typeDownload': 'Download',
        'typeConversion': 'Umwandlung',
        'msgInProgress': ' läuft für Element Nr. %s',
        'colUrl': 'Url',
        'colState': 'Status',
        'colStatusCode': 'Statuscode',
        'colSaveAs': 'Speicherort',
        'colActions': 'Aktionen',
        'ctxCopyLink': 'Link-Adresse kopieren',
        'ctxOpenFolder': 'Download-Ordner öffnen',
        'ctxDownloadNow': 'Jetzt herunterladen',
        'ctxConvertMp3': 'In mp3 umwandeln',
        'ctxStop': 'Stopp',
        'ctxRemove': 'Entfernen',
        'ctxDeleteAndRemove': 'Datei löschen und entfernen',
        'menuFile': 'Datei',
        'menuEdit': 'Bearbeiten',
        'menuHelp': 'Hilfe',
        'actionExit': 'Beenden',
        'actionStartWaiting': 'Wartende Links starten',
        'actionStopAll': 'Alle stoppen',
        'actionRemoveAll': 'Alle entfernen',
        'actionPreferences': 'Einstellungen',
        'actionCheckUpdates': 'Nach Updates suchen',
        'actionAbout': 'Über',
        'prefsTitle': 'Einstellungen',
        'downloadFolderLabel': 'Download-Ordner',
        'selectButton': 'Auswählen',
        'videoGroupLabel': 'Video',
        'convNever': 'Nie umwandeln',
        'convDeleteVideo': 'Immer in Audio umwandeln und Video löschen',
        'convKeepVideo': 'Immer in Audio umwandeln und Video behalten',
        'afterDownloadLabel': 'Nach dem Download',
        'doOpenFolder': 'Download-Ordner öffnen',
        'doNothing': 'Nichts tun',
        'languageLabel': 'Sprache',
    },

    # cinese semplificato
    'zh': {
        'aboutVersion': '版本：%s',
        'aboutWebsite': '网站：{website}',
        'btnDefault': ' 粘贴并下载',
        'btnReverse': ' 请稍候...',
        'ffmpegRequired': '运行 {appName} 需要 FFmpeg。<br>请访问 <a href="https://ffmpeg.org/">https://ffmpeg.org/</a> 下载',
        'downloadPathError': '下载文件夹不可访问',
        'internetError': '没有网络连接，可能被防病毒软件或防火墙拦截',
        'noLinks': '没有等待下载的链接',
        'txtUpdatesHtml': '新版本 <br><b>%s</b><br> 已发布！<br><br>请访问 {website}<br>',
        'txtUpdatesTxt': '新版本 %s 可用！',
        'txtUpdatesNo': '{appName} 已是最新版本<br>',
        'txtUpdatesError': '无法检查更新',
        'ytDlpUpdating': '正在更新内部库...',
        'ytDlpUpdateDone': '内部库已更新',
        'confirmExitTitle': '确认退出',
        'confirmExitMsg': '有一个下载任务正在进行。确定要退出吗？该下载将被中止。',
        'restartRequired': '重启 {appName} 以使语言更改生效。',
        'titleRequirements': '所需组件',
        'titleError': '错误',
        'titleUpdates': '更新',
        'titleRestart': '需要重启',
        'msgContentCopied': '内容已复制',
        'msgFoundLinks': '找到 %s 个有效链接',
        'msgNoValidLinks': '未找到有效链接',
        'msgInvalidPastylink': '链接复制有误，请返回 Pastylink 重试',
        'msgDownloadStarted': '下载已开始...',
        'msgDownloadFinished': '下载在 %s 秒内完成',
        'typeDownload': '下载',
        'typeConversion': '转换',
        'msgInProgress': ' 正在处理第 %s 项',
        'colUrl': '网址',
        'colState': '状态',
        'colStatusCode': '状态码',
        'colSaveAs': '保存为',
        'colActions': '操作',
        'ctxCopyLink': '复制链接地址',
        'ctxOpenFolder': '打开下载文件夹',
        'ctxDownloadNow': '立即下载',
        'ctxConvertMp3': '转换为mp3',
        'ctxStop': '停止',
        'ctxRemove': '移除',
        'ctxDeleteAndRemove': '删除文件并移除',
        'menuFile': '文件',
        'menuEdit': '编辑',
        'menuHelp': '帮助',
        'actionExit': '退出',
        'actionStartWaiting': '开始等待中的链接',
        'actionStopAll': '全部停止',
        'actionRemoveAll': '全部移除',
        'actionPreferences': '首选项',
        'actionCheckUpdates': '检查更新',
        'actionAbout': '关于',
        'prefsTitle': '首选项',
        'downloadFolderLabel': '下载文件夹',
        'selectButton': '选择',
        'videoGroupLabel': '视频',
        'convNever': '从不转换',
        'convDeleteVideo': '始终转换为音频并删除视频',
        'convKeepVideo': '始终转换为音频并保留视频',
        'afterDownloadLabel': '下载后',
        'doOpenFolder': '打开下载文件夹',
        'doNothing': '不执行任何操作',
        'languageLabel': '语言',
    },

    # giapponese
    'ja': {
        'aboutVersion': 'バージョン: %s',
        'aboutWebsite': 'ウェブサイト: {website}',
        'btnDefault': ' 貼り付けてダウンロード',
        'btnReverse': ' お待ちください...',
        'ffmpegRequired': '{appName} の実行には FFmpeg が必要です。<br><a href="https://ffmpeg.org/">https://ffmpeg.org/</a> からダウンロードしてください',
        'downloadPathError': 'ダウンロードフォルダにアクセスできません',
        'internetError': 'インターネット接続がありません。ウイルス対策ソフトやファイアウォールでブロックされている可能性があります',
        'noLinks': 'ダウンロード待ちのリンクはありません',
        'txtUpdatesHtml': '新しいバージョン <br><b>%s</b><br> が利用可能です！<br><br>{website} へ移動<br>',
        'txtUpdatesTxt': '新しいバージョン %s が利用可能です！',
        'txtUpdatesNo': '{appName} は最新の状態です<br>',
        'txtUpdatesError': '更新を確認できません',
        'ytDlpUpdating': '内部ライブラリを更新しています...',
        'ytDlpUpdateDone': '内部ライブラリを更新しました',
        'confirmExitTitle': '終了の確認',
        'confirmExitMsg': 'ダウンロードが進行中です。本当に終了しますか？ダウンロードは中止されます。',
        'restartRequired': '言語の変更を反映するには {appName} を再起動してください。',
        'titleRequirements': '必要条件',
        'titleError': 'エラー',
        'titleUpdates': 'アップデート',
        'titleRestart': '再起動が必要です',
        'msgContentCopied': 'コピーしました',
        'msgFoundLinks': '%s 件の有効なリンクが見つかりました',
        'msgNoValidLinks': '有効なリンクが見つかりませんでした',
        'msgInvalidPastylink': 'リンクのコピーに失敗しました。Pastylinkに戻ってもう一度お試しください',
        'msgDownloadStarted': 'ダウンロードを開始しました...',
        'msgDownloadFinished': 'ダウンロードが %s 秒で完了しました',
        'typeDownload': 'ダウンロード',
        'typeConversion': '変換',
        'msgInProgress': ' 項目 No. %s を処理中',
        'colUrl': 'URL',
        'colState': '状態',
        'colStatusCode': 'ステータスコード',
        'colSaveAs': '保存先',
        'colActions': '操作',
        'ctxCopyLink': 'リンクアドレスをコピー',
        'ctxOpenFolder': 'ダウンロードフォルダを開く',
        'ctxDownloadNow': '今すぐダウンロード',
        'ctxConvertMp3': 'mp3に変換',
        'ctxStop': '停止',
        'ctxRemove': '削除',
        'ctxDeleteAndRemove': 'ファイルを削除して除去',
        'menuFile': 'ファイル',
        'menuEdit': '編集',
        'menuHelp': 'ヘルプ',
        'actionExit': '終了',
        'actionStartWaiting': '待機中のリンクを開始',
        'actionStopAll': 'すべて停止',
        'actionRemoveAll': 'すべて削除',
        'actionPreferences': '環境設定',
        'actionCheckUpdates': '更新を確認',
        'actionAbout': 'このアプリについて',
        'prefsTitle': '環境設定',
        'downloadFolderLabel': 'ダウンロードフォルダ',
        'selectButton': '選択',
        'videoGroupLabel': 'ビデオ',
        'convNever': '変換しない',
        'convDeleteVideo': '常に音声に変換して動画を削除',
        'convKeepVideo': '常に音声に変換して動画を保持',
        'afterDownloadLabel': 'ダウンロード後',
        'doOpenFolder': 'ダウンロードフォルダを開く',
        'doNothing': '何もしない',
        'languageLabel': '言語',
    },
}


class MyText():

    # api
    referers = 'https://pasty.info/other/pasty_downloader/api/referer.json'
    checkUpdates = 'https://pasty.info/other/pasty_downloader/api/checkUpdates.json'
    saveStats = 'https://pasty.info/other/pasty_downloader/api/saveStats/'
    checkIp = 'http://wtfismyip.com/text'

    # info
    appName = 'PastyDownloader'
    orgName = 'Pastylink'
    orgDomain = 'pasty.link'
    website = '<a href="https://pasty.link">pasty.link</a>'

    # files
    pasty_icon = ':/images/paste.png'
    pasty_icon_rev = ':/images/paste_revert.png'
    pasty_favicon = ':/images/favicon.ico'

    LANGUAGES = sorted([
        ('en', 'English'), ('it', 'Italiano'), ('fr', 'Français'),
        ('es', 'Español'), ('de', 'Deutsch'), ('zh', '中文'), ('ja', '日本語'),
    ], key=lambda pair: pair[1])
    DEFAULT_LANGUAGE = 'en'

    @classmethod
    def getLanguage(cls):
        lang = QSettings(cls.orgName, cls.appName).value('language')
        return lang if lang in _TRANSLATIONS else cls.DEFAULT_LANGUAGE

    @classmethod
    def setLanguage(cls, lang):
        QSettings(cls.orgName, cls.appName).setValue('language', lang)
        cls._loadLanguage(lang)

    @classmethod
    def _loadLanguage(cls, lang):
        strings = _TRANSLATIONS.get(lang, _TRANSLATIONS[cls.DEFAULT_LANGUAGE])
        for key, value in strings.items():
            setattr(cls, key, value.format(website=cls.website, appName=cls.appName))


MyText._loadLanguage(MyText.getLanguage())
